[package]
name = "simplex"
version = "0.1.0"
authors = ["lan496 <kohei19950508@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.4.0"
